### ISSUE TITLE
[To park] 22.08.04

### ISSUE THREAD

**Issue by rozenk30** [rozenk30/pse-benchmark#5]
1) State에 mass transfer coeff 다시 확인 + 기공 변수 확인
2) MATLAB에서 simulation 코드 작성

**Comment by rozenk30** [comment]
미안한데, 위에 2번 하기 전에 // 엑셀로 부터 input 데이터 읽어와서 기존의 MATLAB 코드 시뮬레이션 하고, 데이터 vs 시뮬레이션 결과 그림 그리는거 먼저 부탁합니다...

**Comment by hmin1226** [comment]
-mass transfer coefficient는 V_s, V_m 등에 의존하는 식으로 나타내져서 state로 분류된 것이 아닌가 싶습니다.
